
os:
  - Visual Studio 2017

build:
  verbosity: detailed

configuration:
  - Debug

branches:
  except:
    - /pr\/.+/

environment:
  matrix:
    - BUILD_TESTS: true


install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  ############################################################################
  # Install Ninja
  ############################################################################
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.0-win32-x86.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps\cmake > nul
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

  ############################################################################
  # Setup the path to Clang-cl
  ############################################################################
  - set PATH="C:\Program Files\LLVM\bin";%PATH%
  - clang -v


before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - set CATCH_DIR=%cd%\catch\include
  - mkdir %CATCH_DIR%
  - appveyor DownloadFile https://github.com/philsquared/Catch/releases/download/v1.8.1/catch.hpp -FileName %CATCH_DIR%\catch.hpp
  - cd C:\projects\bit-stl
  - git submodule init
  - git submodule update

build_script:
  - mkdir build
  - cd build
  - cmake .. -GNinja -DCMAKE_CXX_COMPILER=clang -DCMAKE_INCLUDE_PATH=%CATCH_DIR% -DCMAKE_CXX_FLAGS="-fms-compatibility-version=20 -fexceptions -Xclang -fcxx-exceptions -Wall -Wextra -pedantic" -DBIT_BUILD_TESTS=%BUILD_TESTS%
  - cmake --build .
